// Sample data for the ShopOrbit Shopping App
// This data will be automatically populated in Firestore

const sampleData = {
  "users": [
    {
      "email": "admin@ShopOrbit.com",
      "name": "Admin User",
      "role": "admin",
      "profileImage": "",
      "addresses": [],
      "isBlocked": false,
      "isApproved": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "email": "seller1@example.com",
      "name": "Electronics Store",
      "role": "seller",
      "profileImage": "",
      "addresses": ["123 Business St, Tech City, TC 12345"],
      "isBlocked": false,
      "isApproved": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "email": "seller2@example.com",
      "name": "Fashion Hub",
      "role": "seller",
      "profileImage": "",
      "addresses": ["456 Fashion Ave, Style City, SC 67890"],
      "isBlocked": false,
      "isApproved": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "email": "user1@example.com",
      "name": "John Doe",
      "role": "user",
      "profileImage": "",
      "addresses": ["789 Home St, User City, UC 11111"],
      "isBlocked": false,
      "isApproved": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "email": "user2@example.com",
      "name": "Jane Smith",
      "role": "user",
      "profileImage": "",
      "addresses": ["321 Customer Ave, Buyer City, BC 22222"],
      "isBlocked": false,
      "isApproved": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
  ],
  "categories": [
    {
      "name": "Electronics",
      "description": "Electronic devices and accessories",
      "imageUrl":
          "https://via.placeholder.com/200x200/2196F3/FFFFFF?text=Electronics",
      "subcategories": [
        "Smartphones",
        "Laptops",
        "Tablets",
        "Headphones",
        "Cameras",
      ],
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "name": "Fashion",
      "description": "Clothing and accessories",
      "imageUrl":
          "https://via.placeholder.com/200x200/E91E63/FFFFFF?text=Fashion",
      "subcategories": [
        "Men's Clothing",
        "Women's Clothing",
        "Shoes",
        "Accessories",
      ],
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "name": "Home & Garden",
      "description": "Home improvement and garden supplies",
      "imageUrl": "https://via.placeholder.com/200x200/4CAF50/FFFFFF?text=Home",
      "subcategories": ["Furniture", "Decor", "Kitchen", "Garden", "Tools"],
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "name": "Sports & Outdoors",
      "description": "Sports equipment and outdoor gear",
      "imageUrl":
          "https://via.placeholder.com/200x200/FF9800/FFFFFF?text=Sports",
      "subcategories": [
        "Fitness",
        "Outdoor Recreation",
        "Team Sports",
        "Water Sports",
      ],
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "name": "Books & Media",
      "description": "Books, movies, and digital media",
      "imageUrl":
          "https://via.placeholder.com/200x200/9C27B0/FFFFFF?text=Books",
      "subcategories": ["Books", "Movies", "Music", "Games"],
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
  ],
  "products": [
    {
      "sellerId": "seller1@example.com",
      "name": "iPhone 15 Pro",
      "description":
          "Latest iPhone with advanced camera system and A17 Pro chip",
      "price": 999.99,
      "images": [
        "https://via.placeholder.com/400x400/000000/FFFFFF?text=iPhone+15+Pro",
        "https://via.placeholder.com/400x400/333333/FFFFFF?text=iPhone+Back",
      ],
      "category": "Electronics",
      "subcategory": "Smartphones",
      "brand": "Apple",
      "inventory": 50,
      "averageRating": 4.8,
      "reviewCount": 125,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller1@example.com",
      "name": "Samsung Galaxy S24",
      "description":
          "Flagship Android smartphone with excellent display and camera",
      "price": 849.99,
      "images": [
        "https://via.placeholder.com/400x400/1565C0/FFFFFF?text=Galaxy+S24",
        "https://via.placeholder.com/400x400/0D47A1/FFFFFF?text=Galaxy+Back",
      ],
      "category": "Electronics",
      "subcategory": "Smartphones",
      "brand": "Samsung",
      "inventory": 75,
      "averageRating": 4.6,
      "reviewCount": 98,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller1@example.com",
      "name": "MacBook Pro 14\"",
      "description": "Professional laptop with M3 chip and Retina display",
      "price": 1999.99,
      "images": [
        "https://via.placeholder.com/400x400/666666/FFFFFF?text=MacBook+Pro",
        "https://via.placeholder.com/400x400/999999/FFFFFF?text=MacBook+Open",
      ],
      "category": "Electronics",
      "subcategory": "Laptops",
      "brand": "Apple",
      "inventory": 25,
      "averageRating": 4.9,
      "reviewCount": 67,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller1@example.com",
      "name": "Sony WH-1000XM5",
      "description": "Premium noise-canceling wireless headphones",
      "price": 399.99,
      "images": [
        "https://via.placeholder.com/400x400/212121/FFFFFF?text=Sony+Headphones",
        "https://via.placeholder.com/400x400/424242/FFFFFF?text=Headphones+Side",
      ],
      "category": "Electronics",
      "subcategory": "Headphones",
      "brand": "Sony",
      "inventory": 100,
      "averageRating": 4.7,
      "reviewCount": 234,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller2@example.com",
      "name": "Men's Casual Shirt",
      "description": "Comfortable cotton shirt for everyday wear",
      "price": 29.99,
      "images": [
        "https://via.placeholder.com/400x400/2196F3/FFFFFF?text=Casual+Shirt",
        "https://via.placeholder.com/400x400/1976D2/FFFFFF?text=Shirt+Detail",
      ],
      "category": "Fashion",
      "subcategory": "Men's Clothing",
      "brand": "StyleFit",
      "inventory": 200,
      "averageRating": 4.3,
      "reviewCount": 45,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller2@example.com",
      "name": "Women's Summer Dress",
      "description": "Elegant floral dress perfect for summer occasions",
      "price": 59.99,
      "images": [
        "https://via.placeholder.com/400x400/E91E63/FFFFFF?text=Summer+Dress",
        "https://via.placeholder.com/400x400/C2185B/FFFFFF?text=Dress+Detail",
      ],
      "category": "Fashion",
      "subcategory": "Women's Clothing",
      "brand": "FlowerStyle",
      "inventory": 150,
      "averageRating": 4.5,
      "reviewCount": 78,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller2@example.com",
      "name": "Running Shoes",
      "description": "Comfortable athletic shoes for running and training",
      "price": 89.99,
      "images": [
        "https://via.placeholder.com/400x400/FF5722/FFFFFF?text=Running+Shoes",
        "https://via.placeholder.com/400x400/D84315/FFFFFF?text=Shoes+Side",
      ],
      "category": "Fashion",
      "subcategory": "Shoes",
      "brand": "SportMax",
      "inventory": 120,
      "averageRating": 4.4,
      "reviewCount": 156,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller1@example.com",
      "name": "Wireless Earbuds",
      "description": "True wireless earbuds with active noise cancellation",
      "price": 149.99,
      "images": [
        "https://via.placeholder.com/400x400/000000/FFFFFF?text=Wireless+Earbuds",
        "https://via.placeholder.com/400x400/333333/FFFFFF?text=Earbuds+Case",
      ],
      "category": "Electronics",
      "subcategory": "Headphones",
      "brand": "AudioTech",
      "inventory": 80,
      "averageRating": 4.2,
      "reviewCount": 89,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller2@example.com",
      "name": "Leather Wallet",
      "description": "Genuine leather wallet with multiple card slots",
      "price": 39.99,
      "images": [
        "https://via.placeholder.com/400x400/795548/FFFFFF?text=Leather+Wallet",
        "https://via.placeholder.com/400x400/5D4037/FFFFFF?text=Wallet+Open",
      ],
      "category": "Fashion",
      "subcategory": "Accessories",
      "brand": "LeatherCraft",
      "inventory": 90,
      "averageRating": 4.6,
      "reviewCount": 123,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "sellerId": "seller1@example.com",
      "name": "Smart Watch",
      "description": "Fitness tracking smartwatch with heart rate monitor",
      "price": 199.99,
      "images": [
        "https://via.placeholder.com/400x400/607D8B/FFFFFF?text=Smart+Watch",
        "https://via.placeholder.com/400x400/455A64/FFFFFF?text=Watch+Side",
      ],
      "category": "Electronics",
      "subcategory": "Wearables",
      "brand": "TechFit",
      "inventory": 60,
      "averageRating": 4.3,
      "reviewCount": 67,
      "isActive": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
  ],
  "orders": [
    {
      "userId": "user1@example.com",
      "sellerId": "seller1@example.com",
      "items": [
        {
          "productId": "iphone-15-pro",
          "productName": "iPhone 15 Pro",
          "productImage":
              "https://via.placeholder.com/400x400/000000/FFFFFF?text=iPhone+15+Pro",
          "price": 999.99,
          "quantity": 1,
        },
      ],
      "totalAmount": 999.99,
      "status": "delivered",
      "shippingAddress": "789 Home St, User City, UC 11111",
      "paymentMethod": "Credit Card",
      "isPaid": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "userId": "user2@example.com",
      "sellerId": "seller2@example.com",
      "items": [
        {
          "productId": "summer-dress",
          "productName": "Women's Summer Dress",
          "productImage":
              "https://via.placeholder.com/400x400/E91E63/FFFFFF?text=Summer+Dress",
          "price": 59.99,
          "quantity": 1,
        },
        {
          "productId": "running-shoes",
          "productName": "Running Shoes",
          "productImage":
              "https://via.placeholder.com/400x400/FF5722/FFFFFF?text=Running+Shoes",
          "price": 89.99,
          "quantity": 1,
        },
      ],
      "totalAmount": 149.98,
      "status": "shipped",
      "shippingAddress": "321 Customer Ave, Buyer City, BC 22222",
      "paymentMethod": "PayPal",
      "isPaid": true,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "userId": "user1@example.com",
      "sellerId": "seller1@example.com",
      "items": [
        {
          "productId": "sony-headphones",
          "productName": "Sony WH-1000XM5",
          "productImage":
              "https://via.placeholder.com/400x400/212121/FFFFFF?text=Sony+Headphones",
          "price": 399.99,
          "quantity": 1,
        },
      ],
      "totalAmount": 399.99,
      "status": "pending",
      "shippingAddress": "789 Home St, User City, UC 11111",
      "paymentMethod": "Cash on Delivery",
      "isPaid": false,
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
  ],
  "reviews": [
    {
      "userId": "user1@example.com",
      "userName": "John Doe",
      "userImage": "",
      "productId": "iphone-15-pro",
      "rating": 5.0,
      "comment":
          "Excellent phone! The camera quality is amazing and the performance is top-notch.",
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "userId": "user2@example.com",
      "userName": "Jane Smith",
      "userImage": "",
      "productId": "summer-dress",
      "rating": 4.0,
      "comment":
          "Beautiful dress and great quality fabric. Fits perfectly as described.",
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "userId": "user1@example.com",
      "userName": "John Doe",
      "userImage": "",
      "productId": "sony-headphones",
      "rating": 5.0,
      "comment":
          "Best noise-canceling headphones I've ever used. Perfect for travel.",
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
    {
      "userId": "user2@example.com",
      "userName": "Jane Smith",
      "userImage": "",
      "productId": "running-shoes",
      "rating": 4.0,
      "comment": "Very comfortable for running. Good cushioning and support.",
      "createdAt": "TIMESTAMP",
      "updatedAt": "TIMESTAMP",
    },
  ],
};
